/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostCategory = IDL.Variant({
  'notice' : IDL.Null,
  'blog' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Int,
  'author' : IDL.Text,
  'category' : PostCategory,
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, PostCategory],
      [],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostsByCategory' : IDL.Func([PostCategory], [IDL.Vec(Post)], ['query']),
  'updatePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, PostCategory],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostCategory = IDL.Variant({ 'notice' : IDL.Null, 'blog' : IDL.Null });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Int,
    'author' : IDL.Text,
    'category' : PostCategory,
  });
  
  return IDL.Service({
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, PostCategory],
        [],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostsByCategory' : IDL.Func([PostCategory], [IDL.Vec(Post)], ['query']),
    'updatePost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PostCategory,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };